### ISSUE TITLE
Error on latest version

### ISSUE THREAD

**Issue by pboling** [standardrb/standard-performance#7]
I'm not sure what I am doing wrong, or what change may have triggered this, or if it is related to this library at all... but I have seen two errors, depending on how I tweak my configs.

```
❯ bundle exec rubocop -V
Error: `Performance` cops have been extracted to the `rubocop-performance` gem.
(obsolete configuration found in /Users/pboling/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/standard-performance-1.1.0/config/base.yml, please update it) 
```

And

```
❯ bundle exec rubocop -V
Error: `Performance` cops have been extracted to the `rubocop-performance` gem.
(obsolete configuration found in /Users/pboling/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-performance-1.18.0/config/default.yml, please update it)
```

In both cases the error is absolutely bonkers, because it's not even relevant to anything.  All my configs, and all standard-performance's configs, do, is enable or disable, or configure rubocop-performance's cops, and that should be allowed, even expected, behavior!

**Comment by pboling** [comment]
I was able to get this to go away with additional configuration tweaks.  I think this may have been caused by doubly loading linter gems or their configs, accidentally.  Can't repro anymore.

**Comment by dgmora** [comment]
I've got this issue with  standard 1.37.0 and standard-performance 1.4.0 and 

```
❯ bundle exec rubocop -V
1.64.1 (using Parser 3.3.3.0, rubocop-ast 1.31.3, running on ruby 3.3.2) [arm64-darwin23]
```

This happens when I had the following `rubocop.yml`:

```yml
require:
  - standard
  - standard-performance

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
```
When I deleted the file it stopped happening. I had this because it's what the [README says](https://github.com/standardrb/standard?tab=readme-ov-file#running-standards-rules-via-rubocop)
